import type { CSSProperties } from 'vue';

// One palette for every admin page; the same values as the config and courier
// admin screens so the shell reads as one surface.
export const styles: Record<string, CSSProperties> = {
	shell: {
		display: 'flex',
		minHeight: '100vh',
		fontFamily: 'system-ui, sans-serif',
		color: '#111',
	},
	nav: { width: '220px', borderRight: '1px solid #eee', padding: '16px', flexShrink: 0 },
	navGroup: {
		fontSize: '11px',
		textTransform: 'uppercase',
		letterSpacing: '0.6px',
		color: '#888',
		margin: '16px 0 6px',
	},
	navItem: {
		display: 'block',
		width: '100%',
		textAlign: 'left',
		background: 'none',
		border: 'none',
		borderRadius: '6px',
		padding: '6px 8px',
		cursor: 'pointer',
		fontSize: '14px',
		color: '#111',
	},
	navItemActive: { background: '#f3f4f6', fontWeight: 600 },
	main: { flex: 1, padding: '24px', maxWidth: '960px' },
	container: { padding: '24px', maxWidth: '960px' },
	title: { fontSize: '20px', fontWeight: 700, marginTop: 0, marginBottom: '12px' },
	subtitle: { fontSize: '15px', fontWeight: 600, marginTop: '24px', marginBottom: '8px' },
	status: { padding: '12px', color: '#666' },
	error: { color: '#e11d48', marginBottom: '12px', fontSize: '14px' },
	ok: { color: '#15803d', fontWeight: 600 },
	bad: { color: '#e11d48', fontWeight: 600 },
	advice: { color: '#b45309' },
	muted: { color: '#666', fontSize: '13px' },
	mono: { fontFamily: 'ui-monospace, monospace', fontSize: '13px' },
	table: { width: '100%', borderCollapse: 'collapse', fontSize: '14px' },
	th: {
		textAlign: 'left',
		borderBottom: '1px solid #ddd',
		padding: '6px 8px',
		fontWeight: 600,
		color: '#444',
	},
	td: { borderBottom: '1px solid #eee', padding: '6px 8px', verticalAlign: 'top' },
	list: { listStyle: 'none', padding: 0, margin: 0 },
	row: { borderBottom: '1px solid #eee', padding: '8px 0' },
	badge: {
		display: 'inline-block',
		borderRadius: '999px',
		padding: '1px 8px',
		fontSize: '12px',
		background: '#f3f4f6',
	},
	button: {
		background: 'none',
		border: '1px solid #ddd',
		borderRadius: '8px',
		padding: '4px 10px',
		cursor: 'pointer',
		fontSize: '13px',
	},
	toolbar: { display: 'flex', gap: '8px', alignItems: 'center', marginBottom: '12px' },
};
