import type { CSSProperties } from 'react';

// One palette for every admin page; the same values as the config and courier
// admin screens so the shell reads as one surface.
export const styles: Record<string, CSSProperties> = {
	shell: {
		display: 'flex',
		minHeight: '100vh',
		fontFamily: 'system-ui, sans-serif',
		color: '#111',
	},
	nav: { width: 220, borderRight: '1px solid #eee', padding: 16, flexShrink: 0 },
	navGroup: {
		fontSize: 11,
		textTransform: 'uppercase',
		letterSpacing: 0.6,
		color: '#888',
		margin: '16px 0 6px',
	},
	navItem: {
		display: 'block',
		width: '100%',
		textAlign: 'left',
		background: 'none',
		border: 'none',
		borderRadius: 6,
		padding: '6px 8px',
		cursor: 'pointer',
		fontSize: 14,
		color: '#111',
	},
	navItemActive: { background: '#f3f4f6', fontWeight: 600 },
	main: { flex: 1, padding: 24, maxWidth: 960 },
	container: { padding: 24, maxWidth: 960 },
	title: { fontSize: 20, fontWeight: 700, marginTop: 0, marginBottom: 12 },
	subtitle: { fontSize: 15, fontWeight: 600, marginTop: 24, marginBottom: 8 },
	status: { padding: 12, color: '#666' },
	error: { color: '#e11d48', marginBottom: 12, fontSize: 14 },
	ok: { color: '#15803d', fontWeight: 600 },
	bad: { color: '#e11d48', fontWeight: 600 },
	advice: { color: '#b45309' },
	muted: { color: '#666', fontSize: 13 },
	mono: { fontFamily: 'ui-monospace, monospace', fontSize: 13 },
	table: { width: '100%', borderCollapse: 'collapse', fontSize: 14 },
	th: {
		textAlign: 'left',
		borderBottom: '1px solid #ddd',
		padding: '6px 8px',
		fontWeight: 600,
		color: '#444',
	},
	td: { borderBottom: '1px solid #eee', padding: '6px 8px', verticalAlign: 'top' },
	list: { listStyle: 'none', padding: 0, margin: 0 },
	row: { borderBottom: '1px solid #eee', padding: '8px 0' },
	badge: {
		display: 'inline-block',
		borderRadius: 999,
		padding: '1px 8px',
		fontSize: 12,
		background: '#f3f4f6',
	},
	button: {
		background: 'none',
		border: '1px solid #ddd',
		borderRadius: 8,
		padding: '4px 10px',
		cursor: 'pointer',
		fontSize: 13,
	},
	toolbar: { display: 'flex', gap: 8, alignItems: 'center', marginBottom: 12 },
};
