import type { CSSProperties } from 'vue';

export const styles: Record<string, CSSProperties> = {
	container: { padding: '24px', maxWidth: '640px' },
	title: { fontSize: '20px', fontWeight: 700, marginTop: '24px', marginBottom: '12px' },
	editorTitle: { fontSize: '24px', fontWeight: 700 },
	meta: { fontSize: '13px', color: 'var(--fonderie-text-muted,#5c5c5c)', marginBottom: '16px' },
	status: { padding: '12px', color: 'var(--fonderie-text-muted,#5c5c5c)' },
	error: { color: 'var(--fonderie-danger,#e00)', marginBottom: '12px', fontSize: '14px' },
	list: { listStyle: 'none', padding: '0', margin: '0' },
	row: {
		display: 'flex',
		alignItems: 'center',
		gap: '12px',
		borderBottom: '1px solid var(--fonderie-border-light,#f5f5f5)',
		padding: '10px 0',
	},
	revisionRow: {
		display: 'flex',
		justifyContent: 'space-between',
		alignItems: 'center',
		padding: '8px 0',
		borderBottom: '1px solid var(--fonderie-border-light,#f5f5f5)',
		fontSize: '13px',
	},
	rowButton: {
		flex: '1',
		display: 'flex',
		justifyContent: 'space-between',
		background: 'none',
		border: 'none',
		cursor: 'pointer',
		textAlign: 'left',
		padding: '0',
	},
	key: { fontSize: '14px', fontWeight: 600 },
	env: { fontSize: '13px', color: 'var(--fonderie-text-muted,#5c5c5c)' },
	revealed: { fontSize: '13px', fontFamily: 'var(--fonderie-mono,ui-monospace,SFMono-Regular,Menlo,Monaco,Consolas,"Liberation Mono","Courier New",monospace)', color: 'var(--fonderie-text,#171717)', minWidth: '100px' },
	revealBox: { display: 'flex', alignItems: 'center', gap: '12px', marginBottom: '16px' },
	revealButton: {
		background: 'none',
		border: '1px solid var(--fonderie-border,#e0e0e0)',
		borderRadius: '8px',
		padding: '4px 10px',
		fontSize: '12px',
		cursor: 'pointer',
	},
	form: { display: 'flex', flexDirection: 'column', gap: '4px' },
	label: { fontSize: '13px', fontWeight: 600, marginTop: '12px' },
	input: { border: '1px solid var(--fonderie-border,#e0e0e0)', borderRadius: '8px', padding: '10px', fontSize: '14px' },
	textarea: {
		border: '1px solid var(--fonderie-border,#e0e0e0)',
		borderRadius: '8px',
		padding: '10px',
		fontSize: '14px',
		fontFamily: 'var(--fonderie-mono,ui-monospace,SFMono-Regular,Menlo,Monaco,Consolas,"Liberation Mono","Courier New",monospace)',
	},
	button: {
		marginTop: '16px',
		backgroundColor: 'var(--fonderie-text,#171717)',
		color: 'var(--fonderie-surface,#fff)',
		padding: '10px 20px',
		borderRadius: '8px',
		border: 'none',
		fontSize: '14px',
		fontWeight: 600,
		cursor: 'pointer',
		alignSelf: 'flex-start',
	},
	revisions: { marginTop: '32px' },
	subtitle: { fontSize: '16px', fontWeight: 600, marginBottom: '8px' },
	listContainer: { padding: '24px', maxWidth: '880px' },
	heading: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginTop: '24px' },
	headingTitle: { fontSize: '20px', fontWeight: 700, margin: '0' },
	hint: { fontSize: '13px', color: 'var(--fonderie-text-muted,#5c5c5c)', margin: '4px 0 12px' },
	empty: { fontSize: '14px', color: 'var(--fonderie-text-muted,#5c5c5c)', padding: '16px 0', borderTop: '1px solid var(--fonderie-border-light,#f5f5f5)' },
	newButton: {
		backgroundColor: 'var(--fonderie-text,#171717)',
		color: 'var(--fonderie-surface,#fff)',
		padding: '6px 14px',
		borderRadius: '8px',
		border: 'none',
		fontSize: '13px',
		fontWeight: 600,
		cursor: 'pointer',
	},
	valuePreview: { flex: '1', margin: '0 12px', fontSize: '13px', color: 'var(--fonderie-text,#171717)', fontFamily: 'var(--fonderie-mono,ui-monospace,SFMono-Regular,Menlo,Monaco,Consolas,"Liberation Mono","Courier New",monospace)', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' },
	badge: { fontSize: '11px', padding: '2px 6px', borderRadius: '6px', border: '1px solid var(--fonderie-border,#e0e0e0)', color: 'var(--fonderie-text-muted,#5c5c5c)', marginRight: '12px' },
	toggle: { display: 'flex', alignItems: 'center', gap: '8px', fontSize: '14px', padding: '6px 0' },
	detected: { display: 'flex', alignItems: 'center', gap: '16px', fontSize: '13px', color: 'var(--fonderie-text-muted,#5c5c5c)', marginTop: '6px' },
	inline: { display: 'flex', alignItems: 'center', gap: '6px' },
	linkButton: { background: 'none', border: 'none', padding: '0', fontSize: '13px', color: 'var(--fonderie-link,#0b6)', cursor: 'pointer', textDecoration: 'underline' },
	warning: { fontSize: '13px', color: 'var(--fonderie-warning,#a15c00)', marginTop: '6px' },
};
