import type { CSSProperties } from 'vue';

export const styles: Record<string, CSSProperties> = {
	container: { padding: '24px', maxWidth: '640px' },
	title: { fontSize: '20px', fontWeight: 700, marginTop: '24px', marginBottom: '12px' },
	editorTitle: { fontSize: '24px', fontWeight: 700 },
	meta: { fontSize: '13px', color: '#666', marginBottom: '16px' },
	status: { padding: '12px', color: '#666' },
	error: { color: '#e11d48', marginBottom: '12px', fontSize: '14px' },
	list: { listStyle: 'none', padding: '0', margin: '0' },
	row: {
		display: 'flex',
		alignItems: 'center',
		gap: '12px',
		borderBottom: '1px solid #eee',
		padding: '10px 0',
	},
	revisionRow: {
		display: 'flex',
		justifyContent: 'space-between',
		alignItems: 'center',
		padding: '8px 0',
		borderBottom: '1px solid #eee',
		fontSize: '13px',
	},
	rowButton: {
		flex: '1',
		display: 'flex',
		justifyContent: 'space-between',
		background: 'none',
		border: 'none',
		cursor: 'pointer',
		textAlign: 'left',
		padding: '0',
	},
	key: { fontSize: '14px', fontWeight: 600 },
	env: { fontSize: '13px', color: '#666' },
	revealed: { fontSize: '13px', fontFamily: 'monospace', color: '#333', minWidth: '100px' },
	revealBox: { display: 'flex', alignItems: 'center', gap: '12px', marginBottom: '16px' },
	revealButton: {
		background: 'none',
		border: '1px solid #ddd',
		borderRadius: '8px',
		padding: '4px 10px',
		fontSize: '12px',
		cursor: 'pointer',
	},
	form: { display: 'flex', flexDirection: 'column', gap: '4px' },
	label: { fontSize: '13px', fontWeight: 600, marginTop: '12px' },
	input: { border: '1px solid #ddd', borderRadius: '8px', padding: '10px', fontSize: '14px' },
	textarea: {
		border: '1px solid #ddd',
		borderRadius: '8px',
		padding: '10px',
		fontSize: '14px',
		fontFamily: 'monospace',
	},
	button: {
		marginTop: '16px',
		backgroundColor: '#000',
		color: '#fff',
		padding: '10px 20px',
		borderRadius: '8px',
		border: 'none',
		fontSize: '14px',
		fontWeight: 600,
		cursor: 'pointer',
		alignSelf: 'flex-start',
	},
	revisions: { marginTop: '32px' },
	subtitle: { fontSize: '16px', fontWeight: 600, marginBottom: '8px' },
};
