import type { CSSProperties } from 'vue';

export const styles: Record<string, CSSProperties> = {
	container: { padding: '24px', maxWidth: '640px' },
	title: { fontSize: '24px', fontWeight: 700, marginBottom: '16px' },
	subtitle: { fontSize: '16px', fontWeight: 600, marginTop: '32px', marginBottom: '8px' },
	secretBanner: {
		background: '#fef3c7',
		borderRadius: '8px',
		padding: '12px',
		fontSize: '13px',
		marginBottom: '16px',
		wordBreak: 'break-all',
	},
	form: { display: 'flex', gap: '8px', marginBottom: '16px' },
	editForm: { display: 'flex', flexDirection: 'column', gap: '4px' },
	label: { fontSize: '13px', fontWeight: 600, marginTop: '12px' },
	input: {
		flex: '1',
		border: '1px solid #ddd',
		borderRadius: '8px',
		padding: '10px',
		fontSize: '14px',
	},
	createButton: {
		backgroundColor: '#000',
		color: '#fff',
		padding: '0 16px',
		borderRadius: '8px',
		border: 'none',
		fontSize: '14px',
		fontWeight: 600,
		cursor: 'pointer',
	},
	button: {
		marginTop: '16px',
		backgroundColor: '#000',
		color: '#fff',
		padding: '10px 20px',
		borderRadius: '8px',
		border: 'none',
		fontSize: '14px',
		fontWeight: 600,
		cursor: 'pointer',
		alignSelf: 'flex-start',
	},
	checkboxLabel: {
		display: 'flex',
		alignItems: 'center',
		gap: '8px',
		marginTop: '12px',
		fontSize: '14px',
	},
	status: { padding: '12px', color: '#666', fontSize: '13px' },
	error: { color: '#e11d48', marginBottom: '12px', fontSize: '14px' },
	list: { listStyle: 'none', padding: '0', margin: '0' },
	row: {
		display: 'flex',
		alignItems: 'center',
		gap: '8px',
		borderBottom: '1px solid #eee',
		padding: '10px 0',
	},
	deliveryRow: {
		display: 'flex',
		flexDirection: 'column',
		gap: '2px',
		borderBottom: '1px solid #eee',
		padding: '8px 0',
	},
	rowButton: {
		flex: '1',
		display: 'flex',
		justifyContent: 'space-between',
		background: 'none',
		border: 'none',
		cursor: 'pointer',
		textAlign: 'left',
		padding: '0',
	},
	url: { fontSize: '14px', fontWeight: 600 },
	eventType: { fontSize: '14px', fontWeight: 600 },
	meta: { fontSize: '12px', color: '#666' },
	enabled: { fontSize: '12px', color: '#16a34a' },
	disabled: { fontSize: '12px', color: '#999' },
	smallButton: {
		background: 'none',
		border: '1px solid #ddd',
		borderRadius: '8px',
		padding: '4px 10px',
		fontSize: '12px',
		cursor: 'pointer',
	},
	deleteButton: {
		background: 'none',
		border: '1px solid #ddd',
		borderRadius: '8px',
		padding: '4px 10px',
		fontSize: '12px',
		cursor: 'pointer',
		color: '#e11d48',
	},
	link: {
		marginTop: '24px',
		background: 'none',
		border: 'none',
		color: '#666',
		cursor: 'pointer',
		fontSize: '14px',
	},
};
