export type {
	CustomerLabelType,
	CustomerSex,
	CustomersClient,
	CustomerType,
	IAddAddressInput,
	IAddEmailInput,
	IAddPhoneInput,
	IAddRelationshipInput,
	IAddressDTO,
	IBlacklistCustomerInput,
	ICreateCustomerInput,
	ICustomerAddressDTO,
	ICustomerDetailD2DTO,
	ICustomerDetailDTO,
	ICustomerDTO,
	ICustomerEmailDTO,
	ICustomerLabelDTO,
	ICustomerNoteDTO,
	ICustomerPhoneDTO,
	ICustomerRelationshipDTO,
	ICustomerRelationshipExpandedD2DTO,
	ICustomerRelationshipExpandedDTO,
	ICustomerShallowDTO,
	IGetCustomerInput,
	IListCustomersInput,
	IUpdateCustomerInput,
} from '@fonderie/client';
export { FonderieApiError } from '@fonderie/client';
export type { ICustomerSectionOptions } from './hooks/section-options';
export type {
	IUseCustomerAddressesReturn,
	IUseCustomerEmailsReturn,
	IUseCustomerLabelsReturn,
	IUseCustomerNotesReturn,
	IUseCustomerPhonesReturn,
	IUseCustomerRelationshipsReturn,
	IUseCustomerReturn,
	IUseCustomersReturn,
	IUseCustomerTagsReturn,
	IUseDeletedCustomersReturn,
} from './hooks';
export {
	useCustomer,
	useCustomerAddresses,
	useCustomerEmails,
	useCustomerLabels,
	useCustomerNotes,
	useCustomerPhones,
	useCustomerRelationships,
	useCustomers,
	useCustomerTags,
	useDeletedCustomers,
} from './hooks';
