import type { CSSProperties } from 'vue';

export const styles: Record<string, CSSProperties> = {
	container: { padding: '24px', maxWidth: '480px' },
	header: {
		display: 'flex',
		justifyContent: 'space-between',
		alignItems: 'center',
		marginBottom: '16px',
	},
	title: { fontSize: '24px', fontWeight: 700 },
	subtitle: { fontSize: '16px', fontWeight: 600, marginTop: '24px', marginBottom: '8px' },
	status: { padding: '24px', textAlign: 'center', color: '#666' },
	error: { color: '#e11d48', marginBottom: '12px', fontSize: '14px' },
	form: { display: 'flex', gap: '8px', marginBottom: '12px' },
	input: {
		flex: '1',
		border: '1px solid #ddd',
		borderRadius: '8px',
		padding: '12px',
		fontSize: '14px',
	},
	button: {
		backgroundColor: '#000',
		color: '#fff',
		padding: '0 16px',
		borderRadius: '8px',
		border: 'none',
		fontSize: '14px',
		fontWeight: 600,
		cursor: 'pointer',
	},
	inviteButton: {
		backgroundColor: '#000',
		color: '#fff',
		padding: '8px 16px',
		borderRadius: '8px',
		border: 'none',
		fontSize: '14px',
		fontWeight: 600,
		cursor: 'pointer',
	},
	list: { listStyle: 'none', padding: '0', margin: '0' },
	row: {
		display: 'flex',
		justifyContent: 'space-between',
		alignItems: 'center',
		padding: '12px 0',
		borderBottom: '1px solid #eee',
	},
	userId: { fontSize: '14px', fontWeight: 600 },
	email: { fontSize: '14px', fontWeight: 600 },
	role: { fontSize: '12px', color: '#666' },
	meta: { fontSize: '12px', color: '#666' },
	removeButton: {
		background: 'none',
		border: '1px solid #ddd',
		borderRadius: '8px',
		padding: '6px 12px',
		fontSize: '13px',
		cursor: 'pointer',
		color: '#e11d48',
	},
	cancelButton: {
		background: 'none',
		border: '1px solid #ddd',
		borderRadius: '8px',
		padding: '4px 10px',
		fontSize: '12px',
		cursor: 'pointer',
	},
	link: {
		marginTop: '24px',
		background: 'none',
		border: 'none',
		color: '#666',
		cursor: 'pointer',
		fontSize: '14px',
	},
};
