import type { CSSProperties } from 'vue';

export const styles: Record<string, CSSProperties> = {
	container: { padding: '24px' },
	// Two columns, always: editor left, rendered result right. Stacking the
	// preview under a long form hid it below the fold.
	split: { display: 'grid', gridTemplateColumns: 'minmax(0, 1fr) minmax(0, 1fr)', gap: '24px', alignItems: 'start' },
	column: { minWidth: '0', display: 'flex', flexDirection: 'column' },
	// Pinned while the form scrolls, so the preview stays in view as you edit.
	previewColumn: { minWidth: '0', display: 'flex', flexDirection: 'column', position: 'sticky', top: '16px' },
	saveRow: { display: 'flex', alignItems: 'center', gap: '12px', marginTop: '16px' },
	previewHeader: {
		display: 'flex',
		justifyContent: 'space-between',
		alignItems: 'center',
		marginTop: '12px',
	},
	previewSubject: { fontSize: '14px', fontWeight: '600', margin: '8px 0' },
	previewFrame: {
		width: '100%',
		height: '520px',
		border: '1px solid var(--fonderie-border,#e0e0e0)',
		borderRadius: '8px',
		background: 'var(--fonderie-surface,#fff)',
	},
	previewText: {
		whiteSpace: 'pre-wrap',
		border: '1px solid var(--fonderie-border,#e0e0e0)',
		borderRadius: '8px',
		padding: '12px',
		fontSize: '13px',
		fontFamily: 'var(--fonderie-mono,ui-monospace,SFMono-Regular,Menlo,Monaco,Consolas,"Liberation Mono","Courier New",monospace)',
	},
	title: { fontSize: '24px', fontWeight: 700 },
	subtitle: { fontSize: '16px', fontWeight: 600, marginBottom: '8px' },
	meta: { fontSize: '13px', color: 'var(--fonderie-text-muted,#5c5c5c)', marginBottom: '16px' },
	status: { padding: '24px', textAlign: 'center', color: 'var(--fonderie-text-muted,#5c5c5c)' },
	error: { color: 'var(--fonderie-danger,#e00)', marginBottom: '12px', fontSize: '14px' },
	list: { listStyle: 'none', padding: '0', margin: '0' },
	row: { borderBottom: '1px solid var(--fonderie-border-light,#f5f5f5)' },
	rowButton: {
		width: '100%',
		display: 'flex',
		justifyContent: 'space-between',
		alignItems: 'center',
		padding: '12px 0',
		background: 'none',
		border: 'none',
		cursor: 'pointer',
		textAlign: 'left',
	},
	type: { fontSize: '14px', fontWeight: 600, flex: '1' },
	locale: { fontSize: '13px', color: 'var(--fonderie-text-muted,#5c5c5c)', marginRight: '16px' },
	active: { fontSize: '12px', color: 'var(--fonderie-accent-strong,#009767)' },
	inactive: { fontSize: '12px', color: 'var(--fonderie-text-muted,#5c5c5c)' },
	form: { display: 'flex', flexDirection: 'column', gap: '4px' },
	label: { fontSize: '13px', fontWeight: 600, marginTop: '12px' },
	input: { border: '1px solid var(--fonderie-border,#e0e0e0)', borderRadius: '8px', padding: '10px', fontSize: '14px' },
	textarea: {
		border: '1px solid var(--fonderie-border,#e0e0e0)',
		borderRadius: '8px',
		padding: '10px',
		fontSize: '14px',
		fontFamily: 'var(--fonderie-mono,ui-monospace,SFMono-Regular,Menlo,Monaco,Consolas,"Liberation Mono","Courier New",monospace)',
	},
	checkboxLabel: {
		display: 'flex',
		alignItems: 'center',
		gap: '8px',
		marginTop: '12px',
		fontSize: '14px',
	},
	button: {
		backgroundColor: 'var(--fonderie-text,#171717)',
		color: 'var(--fonderie-surface,#fff)',
		padding: '10px 20px',
		borderRadius: '8px',
		border: 'none',
		fontSize: '14px',
		fontWeight: 600,
		cursor: 'pointer',
		alignSelf: 'flex-start',
	},
	buttonDisabled: {
		backgroundColor: 'var(--fonderie-border,#e0e0e0)',
		color: 'var(--fonderie-text-muted,#5c5c5c)',
		padding: '10px 20px',
		borderRadius: '8px',
		border: 'none',
		fontSize: '14px',
		fontWeight: 600,
		cursor: 'not-allowed',
		alignSelf: 'flex-start',
	},
	revisions: { marginTop: '32px' },
	revisionRow: {
		display: 'flex',
		justifyContent: 'space-between',
		alignItems: 'center',
		padding: '8px 0',
		borderBottom: '1px solid var(--fonderie-border-light,#f5f5f5)',
		fontSize: '13px',
	},
	rollbackButton: {
		background: 'none',
		border: '1px solid var(--fonderie-border,#e0e0e0)',
		borderRadius: '8px',
		padding: '4px 10px',
		fontSize: '12px',
		cursor: 'pointer',
	},
};
