import type { CSSProperties } from 'vue';

export const styles: Record<string, CSSProperties> = {
	container: { padding: '24px', maxWidth: '640px' },
	title: { fontSize: '24px', fontWeight: 700 },
	subtitle: { fontSize: '16px', fontWeight: 600, marginBottom: '8px' },
	meta: { fontSize: '13px', color: '#666', marginBottom: '16px' },
	status: { padding: '24px', textAlign: 'center', color: '#666' },
	error: { color: '#e11d48', marginBottom: '12px', fontSize: '14px' },
	list: { listStyle: 'none', padding: '0', margin: '0' },
	row: { borderBottom: '1px solid #eee' },
	rowButton: {
		width: '100%',
		display: 'flex',
		justifyContent: 'space-between',
		alignItems: 'center',
		padding: '12px 0',
		background: 'none',
		border: 'none',
		cursor: 'pointer',
		textAlign: 'left',
	},
	type: { fontSize: '14px', fontWeight: 600, flex: '1' },
	locale: { fontSize: '13px', color: '#666', marginRight: '16px' },
	active: { fontSize: '12px', color: '#16a34a' },
	inactive: { fontSize: '12px', color: '#999' },
	form: { display: 'flex', flexDirection: 'column', gap: '4px' },
	label: { fontSize: '13px', fontWeight: 600, marginTop: '12px' },
	input: { border: '1px solid #ddd', borderRadius: '8px', padding: '10px', fontSize: '14px' },
	textarea: {
		border: '1px solid #ddd',
		borderRadius: '8px',
		padding: '10px',
		fontSize: '14px',
		fontFamily: 'monospace',
	},
	checkboxLabel: {
		display: 'flex',
		alignItems: 'center',
		gap: '8px',
		marginTop: '12px',
		fontSize: '14px',
	},
	button: {
		marginTop: '16px',
		backgroundColor: '#000',
		color: '#fff',
		padding: '10px 20px',
		borderRadius: '8px',
		border: 'none',
		fontSize: '14px',
		fontWeight: 600,
		cursor: 'pointer',
		alignSelf: 'flex-start',
	},
	revisions: { marginTop: '32px' },
	revisionRow: {
		display: 'flex',
		justifyContent: 'space-between',
		alignItems: 'center',
		padding: '8px 0',
		borderBottom: '1px solid #eee',
		fontSize: '13px',
	},
	rollbackButton: {
		background: 'none',
		border: '1px solid #ddd',
		borderRadius: '8px',
		padding: '4px 10px',
		fontSize: '12px',
		cursor: 'pointer',
	},
};
