import type { CSSProperties } from 'vue';

export const styles: Record<string, CSSProperties> = {
	container: { padding: '8px 40px 64px', maxWidth: '1400px', boxSizing: 'border-box' },
	// Two columns, always: editor left, rendered result right. Stacking the
	// preview under a long form hid it below the fold.
	split: {
		display: 'grid',
		gridTemplateColumns: 'minmax(0, 1fr) minmax(0, 1fr)',
		gap: '24px',
		alignItems: 'start',
	},
	column: { minWidth: '0', display: 'flex', flexDirection: 'column' },
	// Pinned while the form scrolls, so the preview stays in view as you edit.
	previewColumn: {
		minWidth: '0',
		display: 'flex',
		flexDirection: 'column',
		position: 'sticky',
		top: '16px',
	},
	saveRow: { display: 'flex', alignItems: 'center', gap: '12px', marginTop: '16px' },
	previewHeader: {
		display: 'flex',
		justifyContent: 'space-between',
		alignItems: 'center',
		marginTop: '12px',
	},
	previewSubject: { fontSize: '14px', fontWeight: '600', margin: '8px 0' },
	previewFrame: {
		width: '100%',
		height: '520px',
		border: '1px solid var(--fonderie-border,#e0e0e0)',
		borderRadius: '8px',
		background: 'var(--fonderie-surface,#fff)',
		boxShadow: 'var(--fonderie-shadow-card,0 2px 3px 0 rgba(0,0,0,.05))',
	},
	previewText: {
		whiteSpace: 'pre-wrap',
		border: '1px solid var(--fonderie-border,#e0e0e0)',
		borderRadius: '8px',
		padding: '12px',
		fontSize: '13px',
		fontFamily:
			'var(--fonderie-mono,ui-monospace,SFMono-Regular,Menlo,Monaco,Consolas,"Liberation Mono","Courier New",monospace)',
	},
	title: {
		fontSize: '22px',
		fontWeight: 600,
		margin: '8px 0 4px',
		letterSpacing: 'var(--fonderie-tracking-display,-0.05em)',
		lineHeight: 1.25,
	},
	subtitle: {
		fontSize: '15px',
		fontWeight: 600,
		margin: '0 0 10px',
		letterSpacing: 'var(--fonderie-tracking-display,-0.05em)',
	},
	meta: { fontSize: '13px', color: 'var(--fonderie-text-muted,#5c5c5c)', marginBottom: '20px' },
	status: { padding: '24px 0', color: 'var(--fonderie-text-muted,#5c5c5c)', fontSize: '13.5px' },
	error: {
		color: 'var(--fonderie-danger,#e00)',
		background: 'color-mix(in srgb, var(--fonderie-danger,#e00) 8%, transparent)',
		borderRadius: '6px',
		padding: '8px 12px',
		margin: '8px 0',
		fontSize: '13.5px',
	},
	list: {
		listStyle: 'none',
		padding: '0',
		margin: '0',
		background: 'var(--fonderie-surface,#fff)',
		border: '1px solid var(--fonderie-border,#e0e0e0)',
		borderRadius: 'var(--fonderie-radius-lg,8px)',
		overflow: 'hidden',
		boxShadow: 'var(--fonderie-shadow-card,0 2px 3px 0 rgba(0,0,0,.05))',
	},
	row: { borderBottom: '1px solid var(--fonderie-border-light,#f5f5f5)' },
	rowButton: {
		width: '100%',
		display: 'flex',
		justifyContent: 'space-between',
		alignItems: 'center',
		gap: '16px',
		padding: '13px 16px',
		background: 'none',
		border: 'none',
		cursor: 'pointer',
		textAlign: 'left',
		color: 'var(--fonderie-text,#171717)',
		fontFamily: 'inherit',
	},
	type: {
		fontSize: '13px',
		fontWeight: 600,
		flex: '1',
		fontFamily:
			'var(--fonderie-mono,ui-monospace,SFMono-Regular,Menlo,Monaco,Consolas,"Liberation Mono","Courier New",monospace)',
	},
	locale: { fontSize: '12.5px', color: 'var(--fonderie-text-muted,#5c5c5c)' },
	active: {
		display: 'inline-flex',
		alignItems: 'center',
		gap: '6px',
		borderRadius: '999px',
		padding: '2px 9px 2px 8px',
		fontSize: '12px',
		fontWeight: 600,
		lineHeight: 1.5,
		minWidth: '64px',
		color: 'var(--fonderie-accent-strong,#009767)',
		background: 'color-mix(in srgb, var(--fonderie-accent-strong,#009767) 13%, transparent)',
	},
	inactive: {
		display: 'inline-flex',
		alignItems: 'center',
		gap: '6px',
		borderRadius: '999px',
		padding: '2px 9px 2px 8px',
		fontSize: '12px',
		fontWeight: 600,
		lineHeight: 1.5,
		minWidth: '64px',
		color: 'var(--fonderie-text-muted,#5c5c5c)',
		background: 'color-mix(in srgb, var(--fonderie-text-muted,#5c5c5c) 10%, transparent)',
	},
	form: {
		display: 'flex',
		flexDirection: 'column',
		gap: '4px',
		background: 'var(--fonderie-surface,#fff)',
		border: '1px solid var(--fonderie-border,#e0e0e0)',
		borderRadius: 'var(--fonderie-radius-lg,8px)',
		padding: '6px 20px 20px',
		boxShadow: 'var(--fonderie-shadow-card,0 2px 3px 0 rgba(0,0,0,.05))',
	},
	label: { fontSize: '13px', fontWeight: 500, marginTop: '14px', marginBottom: '2px' },
	input: {
		height: '36px',
		boxSizing: 'border-box',
		border: '1px solid var(--fonderie-border,#e0e0e0)',
		borderRadius: '6px',
		padding: '0 10px',
		fontSize: '13.5px',
		fontFamily: 'inherit',
		background: 'var(--fonderie-surface,#fff)',
		color: 'var(--fonderie-text,#171717)',
	},
	textarea: {
		border: '1px solid var(--fonderie-border,#e0e0e0)',
		borderRadius: '6px',
		padding: '10px',
		fontSize: '13px',
		lineHeight: 1.55,
		background: 'var(--fonderie-surface,#fff)',
		color: 'var(--fonderie-text,#171717)',
		fontFamily:
			'var(--fonderie-mono,ui-monospace,SFMono-Regular,Menlo,Monaco,Consolas,"Liberation Mono","Courier New",monospace)',
	},
	checkboxLabel: {
		display: 'flex',
		alignItems: 'center',
		gap: '8px',
		marginTop: '12px',
		fontSize: '14px',
	},
	button: {
		display: 'inline-flex',
		alignItems: 'center',
		height: '36px',
		boxSizing: 'border-box',
		backgroundColor: 'var(--fonderie-text,#171717)',
		color: 'var(--fonderie-surface,#fff)',
		padding: '0 16px',
		borderRadius: '6px',
		border: '1px solid var(--fonderie-text,#171717)',
		fontSize: '13.5px',
		fontWeight: 600,
		fontFamily: 'inherit',
		alignSelf: 'flex-start',
		cursor: 'pointer',
	},
	buttonDisabled: {
		display: 'inline-flex',
		alignItems: 'center',
		height: '36px',
		boxSizing: 'border-box',
		backgroundColor: 'var(--fonderie-text,#171717)',
		color: 'var(--fonderie-surface,#fff)',
		padding: '0 16px',
		borderRadius: '6px',
		border: '1px solid var(--fonderie-text,#171717)',
		fontSize: '13.5px',
		fontWeight: 600,
		fontFamily: 'inherit',
		alignSelf: 'flex-start',
		opacity: 0.45,
		cursor: 'not-allowed',
	},
	revisions: { marginTop: '32px' },
	revisionRow: {
		display: 'flex',
		justifyContent: 'space-between',
		alignItems: 'center',
		gap: '12px',
		padding: '9px 16px',
		borderBottom: '1px solid var(--fonderie-border-light,#f5f5f5)',
		fontSize: '13px',
	},
	rollbackButton: {
		display: 'inline-flex',
		alignItems: 'center',
		height: '28px',
		boxSizing: 'border-box',
		background: 'var(--fonderie-surface,#fff)',
		color: 'var(--fonderie-text,#171717)',
		border: '1px solid var(--fonderie-border,#e0e0e0)',
		borderRadius: '6px',
		padding: '0 10px',
		fontSize: '12.5px',
		fontWeight: 500,
		fontFamily: 'inherit',
		cursor: 'pointer',
	},
	// Template list: matches @fonderie/vue-admin-screens' shell look with local
	// values — this package sits below the admin screens and cannot import them.
	listContainer: { padding: '32px 40px 64px', maxWidth: '1160px', boxSizing: 'border-box' },
	listTitle: {
		fontSize: '22px',
		fontWeight: 600,
		margin: '0',
		letterSpacing: 'var(--fonderie-tracking-display,-0.05em)',
		lineHeight: 1.25,
	},
	hint: { fontSize: '13.5px', color: 'var(--fonderie-text-muted,#5c5c5c)', margin: '4px 0 24px' },
	dot: { width: '6px', height: '6px', borderRadius: '999px', background: 'currentColor' },
};
