import type { CSSProperties } from 'vue';

export const styles: Record<string, CSSProperties> = {
	container: { padding: '24px', maxWidth: '560px' },
	title: { fontSize: '24px', fontWeight: 700, marginBottom: '16px' },
	subtitle: { fontSize: '16px', fontWeight: 600, marginTop: '24px', marginBottom: '8px' },
	status: { padding: '24px', textAlign: 'center', color: '#666' },
	error: { color: '#e11d48', marginBottom: '12px', fontSize: '14px' },
	searchInput: {
		width: '100%',
		border: '1px solid #ddd',
		borderRadius: '8px',
		padding: '10px',
		fontSize: '14px',
		marginBottom: '16px',
	},
	form: { display: 'flex', flexDirection: 'column', gap: '8px', marginBottom: '16px' },
	editForm: { display: 'flex', flexDirection: 'column', gap: '8px' },
	input: {
		border: '1px solid #ddd',
		borderRadius: '8px',
		padding: '10px',
		fontSize: '14px',
	},
	inlineForm: { display: 'flex', gap: '8px', marginTop: '8px' },
	inlineInput: {
		flex: '1',
		border: '1px solid #ddd',
		borderRadius: '8px',
		padding: '10px',
		fontSize: '14px',
	},
	createButton: {
		backgroundColor: '#000',
		color: '#fff',
		padding: '10px 16px',
		borderRadius: '8px',
		border: 'none',
		fontSize: '14px',
		fontWeight: 600,
		cursor: 'pointer',
	},
	button: {
		backgroundColor: '#000',
		color: '#fff',
		padding: '10px 16px',
		borderRadius: '8px',
		border: 'none',
		fontSize: '14px',
		fontWeight: 600,
		cursor: 'pointer',
	},
	smallButton: {
		background: 'none',
		border: '1px solid #ddd',
		borderRadius: '8px',
		padding: '6px 12px',
		fontSize: '13px',
		cursor: 'pointer',
	},
	list: { listStyle: 'none', padding: '0', margin: '0' },
	row: { borderBottom: '1px solid #eee' },
	rowButton: {
		width: '100%',
		display: 'flex',
		justifyContent: 'space-between',
		alignItems: 'center',
		padding: '12px 0',
		background: 'none',
		border: 'none',
		textAlign: 'left',
		cursor: 'pointer',
		font: 'inherit',
	},
	detailRow: {
		display: 'flex',
		justifyContent: 'space-between',
		alignItems: 'center',
		padding: '8px 0',
		borderBottom: '1px solid #eee',
		fontSize: '14px',
	},
	rowActions: { display: 'flex', gap: '8px' },
	name: { fontSize: '14px', fontWeight: 600 },
	blacklisted: { fontSize: '12px', color: '#e11d48' },
	primary: { fontSize: '11px', color: '#16a34a', marginLeft: '6px' },
	tags: { display: 'flex', flexWrap: 'wrap', gap: '8px' },
	tag: {
		display: 'inline-flex',
		alignItems: 'center',
		gap: '4px',
		backgroundColor: '#f3f4f6',
		borderRadius: '999px',
		padding: '4px 10px',
		fontSize: '13px',
		border: 'none',
		cursor: 'pointer',
	},
	noteRow: {
		display: 'flex',
		justifyContent: 'space-between',
		alignItems: 'flex-start',
		padding: '8px 0',
		borderBottom: '1px solid #eee',
		gap: '8px',
	},
	noteBody: { fontSize: '14px', margin: '0', flex: '1' },
	link: {
		marginTop: '24px',
		background: 'none',
		border: 'none',
		color: '#666',
		fontSize: '14px',
		cursor: 'pointer',
	},
};
